force-app/main/default/objects/ChargingStation__c/ChargingStation__c.object-meta.xml
<CustomObject>
    <label>Charging Station</label>
    <nameField>
        <label>Charging Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charging Stations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargingStation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChargingStation__c/fields/Delivery_Waypoint__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Waypoint__c</fullName>
    <label>Delivery Waypoint</label>
    <referenceTo>DeliveryWaypoint__c</referenceTo>
    <relationshipLabel>Charging Stations</relationshipLabel>
    <relationshipName>Charging_Stations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChargingStation__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChargingStation__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChargingStation__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChargingStation__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryPlan__c/DeliveryPlan__c.object-meta.xml
<CustomObject>
    <label>Delivery Plan</label>
    <nameField>
        <label>Delivery Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Delivery Route Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryRoute__c/fields/DeliveryPlan__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPlan__c</fullName>
    <label>Delivery Plan</label>
    <referenceTo>DeliveryPlan__c</referenceTo>
    <relationshipLabel>Delivery Routes</relationshipLabel>
    <relationshipName>DeliveryRoutes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryWaypoint__c/DeliveryWaypoint__c.object-meta.xml
<CustomObject>
    <label>Delivery Waypoint</label>
    <nameField>
        <displayFormat>DW-{00000000}</displayFormat>
        <label>Delivery Waypoint Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Waypoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryWaypoint__c/fields/DeliveryPlan__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPlan__c</fullName>
    <formula>DeliveryRoute__r.DeliveryPlan__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Plan</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryWaypoint__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <label>Delivery Route</label>
    <referenceTo>DeliveryRoute__c</referenceTo>
    <relationshipLabel>Delivery Waypoints</relationshipLabel>
    <relationshipName>DeliveryWaypoints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryWaypoint__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryWaypoint__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Delivery Waypoints</relationshipLabel>
    <relationshipName>Delivery_Waypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeliveryRouteController.cls
public with sharing class DeliveryRouteController {
  @AuraEnabled
  public static void planDeliveryRoute(Id accountId) {
    try {
      Account account = [
        SELECT Name
        FROM Account
        WHERE Id = :accountId
        WITH SECURITY_ENFORCED
        LIMIT 1
      ];
      RoutePlannerFunction.execute(account.Name);
    } catch (Exception ex) {
      throw new AuraHandledException(ex.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<DeliveryWaypoint__c> getWaypoints(Id deliveryPlanId) {
    try {
      return [
        SELECT
          Name,
          Service__r.Name,
          Service__r.Location__Latitude__s,
          Service__r.Location__Longitude__s,
          Number__c
        FROM DeliveryWaypoint__c
        WHERE DeliveryRoute__r.DeliveryPlan__c = :deliveryPlanId
        WITH SECURITY_ENFORCED
        ORDER BY CreatedDate DESC
      ];
    } catch (Exception ex) {
      throw new AuraHandledException(ex.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<ChargingStation__c> getChargingStations(
    Id deliveryPlanId
  ) {
    try {
      List<ChargingStation__c> chargingStations = [
        SELECT
          Id,
          Name,
          Street_Address__c,
          City__c,
          State__c,
          Zip__c,
          Location__latitude__s,
          Location__longitude__s,
          Distance__c
        FROM ChargingStation__c
        WHERE
          Delivery_Waypoint__r.DeliveryRoute__r.DeliveryPlan__c = :deliveryPlanId
        WITH SECURITY_ENFORCED
        ORDER BY Distance__c
      ];
      return chargingStations;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}