force-app/main/default/objects/DeliveryPlan__c/DeliveryPlan__c.object-meta.xml
<CustomObject>
    <label>Delivery Plan</label>
    <nameField>
        <label>Delivery Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Delivery Route Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryRoute__c/fields/DeliveryPlan__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPlan__c</fullName>
    <label>Delivery Plan</label>
    <referenceTo>DeliveryPlan__c</referenceTo>
    <relationshipLabel>Delivery Routes</relationshipLabel>
    <relationshipName>DeliveryRoutes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryWaypoint__c/DeliveryWaypoint__c.object-meta.xml
<CustomObject>
    <label>Delivery Waypoint</label>
    <nameField>
        <displayFormat>DW-{00000000}</displayFormat>
        <label>Delivery Waypoint Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Waypoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryWaypoint__c/fields/DeliveryPlan__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPlan__c</fullName>
    <formula>DeliveryRoute__r.DeliveryPlan__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Plan</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryWaypoint__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <label>Delivery Route</label>
    <referenceTo>DeliveryRoute__c</referenceTo>
    <relationshipLabel>Delivery Waypoints</relationshipLabel>
    <relationshipName>DeliveryWaypoints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/trigger handlers/DeliveryPlanTriggerHandler.cls
public with sharing class DeliveryPlanTriggerHandler {
  protected List<DeliveryPlan__ChangeEvent> events;
  public DeliveryPlanTriggerHandler(List<DeliveryPlan__ChangeEvent> events) {
    this.events = events;
    handleDeliveryPlan();
  }

  private void handleDeliveryPlan() {
    for (DeliveryPlan__ChangeEvent event : events) {
      EventBus.ChangeEventHeader header = event.ChangeEventHeader;
      if (header.changetype == 'CREATE') {
        handleCreate(header.getRecordIds().get(0));
      }
    }
  }

  private void handleCreate(Id deliveryPlanId) {
    List<DeliveryWaypoint__c> waypoints = [
      SELECT Id
      FROM DeliveryWaypoint__c
      WHERE DeliveryRoute__r.DeliveryPlan__c = :deliveryPlanId
      WITH SECURITY_ENFORCED
    ];

    Integer jobs = waypoints.size();
    if (jobs == 0) {
      System.debug(
        'No waypoints found for this delivery plan. Ignoring execution.'
      );
      // Should we trigger the event to notify the frontend? Maybe
      return;
    }

    // Execute the Job
    ChargingStationsController.execute(waypoints);
  }
}